### ISSUE TITLE
Does it work with BiggerLobby?

### ISSUE THREAD

**Issue by izzy8799** [TIRTAGT/LCDirectLAN#12]

**Comment by TIRTAGT** [comment]
Yes, LCDirectLAN is tested on 6 player lobby with BiggerLobby v2.6.0.

I've noticed that BiggerLobby has a new update (2.7.0), LCDirectLAN support for that is unknown, but you can try.
Let us know if it works when you have tested it on BiggerLobby v2.7.0 :)

**Comment by izzy8799** [comment]
I apologize for the delay in replying, yes it was working. I don't know how it is today, I switched to MoreCompany.
