### ISSUE TITLE
[Issue] found latency patch issues

### ISSUE THREAD

**Issue by CoolLKKPS** [TIRTAGT/LCDirectLAN#6]
that more like a patcher issues i think, still working on my modpack

**Comment by CoolLKKPS** [comment]
[LogOutput.log](https://github.com/TIRTAGT/LCDirectLAN/files/14717528/LogOutput.log)

**Comment by TIRTAGT** [comment]
Interesting, does the issue persist when only LCDirectLAN is activated or loaded ?

I think it's some kind of incompatibility with the mods you added in the profile, if it is, I may need a mod code so I can test the issue on my side.

**Comment by CoolLKKPS** [comment]
uh i just wake up, will need sometime to updating my modpack

**Comment by CoolLKKPS** [comment]
uh sry let u wait for long, i spilled some water on my keyboard and that malfunction for sometime, here

**Comment by CoolLKKPS** [comment]
[Dark Hour - Streamer_1711167335206.zip](https://github.com/TIRTAGT/LCDirectLAN/files/14730490/Dark.Hour.-.Streamer_1711167335206.zip)

**Comment by CoolLKKPS** [comment]
for now i disabled latency patch to let the log not showing error again, u need to enable in the cfg

**Comment by CoolLKKPS** [comment]
u can use this link to check my modpack [Link](https://1drv.ms/f/s!AlwrljXcImfClQt9MgB2BOZ-XA9h?e=cX6g0c)

**Comment by TIRTAGT** [comment]
Thank you for the issue, it seems to be an error that didn't break the Latency Patch, but I figured out what caused it and fixed it because seeing error in the log is annoying.

Sorry for the long delay, finally had time because University is on pause during summer break :D

**Comment by TIRTAGT** [comment]
Will release the fix to thunderstore either today or tommorow.

**Comment by CoolLKKPS** [comment]
uh about time, actually im finishing fix my modpack so uh, will add ur fix tomorrow, already took 7 hrs for my modpack

**Comment by TIRTAGT** [comment]
I have submitted a new release, Thunderstore seems to not instantly accept new releases, so yeah hopefully it's updated on thunderstore by the time you want to fix the modpack.

Thanks for reporting the issue once again :)
