### ISSUE TITLE
[Error  :LCDirectLAN] Cannot find Canvas/MenuContainer/LobbyHostSettings/HostSettingsContainer/HostUsernameField !

### ISSUE THREAD

**Issue by CoolLKKPS** [TIRTAGT/LCDirectLAN#9]
uh well... another bugs

**Comment by CoolLKKPS** [comment]
really easy to find, u just need to click host and confirm

**Comment by TIRTAGT** [comment]
Can you provide me with the configuration file ? I tested that yesterday and it works.

I believe this error looks like the HostUsernameField isn't created, and I forgot to check for that.

**Comment by CoolLKKPS** [comment]
[TIRTAGT.LCDirectLAN.txt](https://github.com/TIRTAGT/LCDirectLAN/files/14895924/TIRTAGT.LCDirectLAN.txt)

**Comment by CoolLKKPS** [comment]
here

**Comment by TIRTAGT** [comment]
Oh wait, is this the latest version of LCDirectLAN ?

The error looks like it is from a latest version, but the configuration doesn't seem like from the new version.

**Comment by CoolLKKPS** [comment]
oh ok will update config

**Comment by TIRTAGT** [comment]
But yeah, I found the issue and it is valid.

If ``CreateHostUsernameInput`` is disabled or unavailable, the host button breaks, and also the join dialog crashes.

So I'm fixing it right now and will release a patch again today

**Comment by TIRTAGT** [comment]
Would you want to test if the new patch works first (Out of thunderstore, I provide the release here)?

Or you prefer the patch to be on thunderstore so you can just update it via your mod manager? I have tested the fix and it seem to work as expected, but if I can get a test before publishing a full release again that would be great :)

**Comment by CoolLKKPS** [comment]
uh prefer test first, i just finishing my lunch

**Comment by TIRTAGT** [comment]
[TIRTAGT-LCDirectLAN-1.1.2.zip](https://github.com/TIRTAGT/LCDirectLAN/files/14896123/TIRTAGT-LCDirectLAN-1.1.2.zip)

Let me know if this works, hopefully it does :)
If it is, then we're ready for another release (haha).

**Comment by CoolLKKPS** [comment]
@TIRTAGT actually still not working

**Comment by CoolLKKPS** [comment]
[TIRTAGT.LCDirectLAN.txt](https://github.com/TIRTAGT/LCDirectLAN/files/14896307/TIRTAGT.LCDirectLAN.txt)

**Comment by CoolLKKPS** [comment]
but this time no error log now, just not work with v50

**Comment by TIRTAGT** [comment]
Interesting, I'm still on v49, will try the pre-release v50 with your configuration

**Comment by CoolLKKPS** [comment]
@TIRTAGT oh wait i think i know now

**Comment by CoolLKKPS** [comment]
let me do more test

**Comment by CoolLKKPS** [comment]
ok only happen if "CreateHostUsernameInput = false", mod won't use the specified name that from the config file now, if "CreateHostUsernameInput = true", users can customize the host name in the host interface

**Comment by TIRTAGT** [comment]
I got jumpscared by the game, got something like an unknown room with "Unable to start, please fix issues".

Can't seem to click "Confirm" on host game, can you host a game ?

----

When you set CreateHostUsernameInput as false, the mod should use ``HostDefaultUsername`` which in your case is ``Lethal Hoster``, it doesn't ?

**Comment by CoolLKKPS** [comment]
yes it doesn't, and in v50, and really recommend update to v50 bc u should check what's changed in v50

**Comment by CoolLKKPS** [comment]
basially nothing change about networking and v50 actually is a good update

**Comment by TIRTAGT** [comment]
Trying to check the problem, I have installed the v50 on steam, I found another issue that when you click "Confirm" on the host button, it doesn't do anything at all when ``CreateHostUsernameInput`` is set to false.

Is that the problem you encounter too ?

And when ``CreateHostUsernameInput`` is set to true, I can host just fine.

**Comment by CoolLKKPS** [comment]
yes ok seems like only happen in v50

**Comment by TIRTAGT** [comment]
I made a little patch and that seem to fix it, would you like to re-test ?

**Comment by CoolLKKPS** [comment]
sure >)

**Comment by TIRTAGT** [comment]
[TIRTAGT-LCDirectLAN-1.1.3.zip](https://github.com/TIRTAGT/LCDirectLAN/files/14896487/TIRTAGT-LCDirectLAN-1.1.3.zip)

Here you go, please let me know if that works

**Comment by CoolLKKPS** [comment]
@TIRTAGT  worked

**Comment by CoolLKKPS** [comment]
fully checked, no error log now

**Comment by TIRTAGT** [comment]
Aha, now it works on v50 too ? looks nice :D

**Comment by CoolLKKPS** [comment]
haha ok going to update my modpack now, still working on that

**Comment by TIRTAGT** [comment]
I will release this version now as 1.1.3, will skip 1.1.2 as that release is broken for v50 haha.

I wasn't expecting LCDirectLAN to work without many changes for v50, but it looks like it works just fine now, which is nice 😄

**Comment by TIRTAGT** [comment]
The new release (1.1.3) is now available on Thunderstore, thank you for reporting the issue :)
